version: '3.8'

services:
  api:
    # build: .
    image: api-api:latest
    container_name: demo_scens_api
    ports:
      - "25376:25376"
    volumes:
      # Persist outputs to the host machine
      - ./outputs:/app/outputs
      # Optional: mount inputs if they change often
      - ./input:/app/input
      - ./submod:/app/submode
      # 挂载routers文件夹
      - ./routers:/app/routers
      # 挂载main.py文件
      - ./main.py:/app/main.py
    restart: unless-stopped
